all: 130226_decode 130225_decode reverse alpha2num

130226_decode: 130226_decode.c libdecode.c


130225_decode: 130225_decode.c libdecode.c

reverse: reverse.c libdecode.c

alpha2num : alpha2num.c libdecode.c
clean:
	rm 130226_decode 130225_decode reverse alpha2num 

